<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-11-18T14:46:25Z" name="Default suite" finished-at="2021-11-18T14:46:27Z" duration-ms="1379">
    <groups>
    </groups>
    <test started-at="2021-11-18T14:46:25Z" name="Default test" finished-at="2021-11-18T14:46:27Z" duration-ms="1379">
      <class name="Testcases.Assign1">
        <test-method is-config="true" signature="beforeclass()[pri:0, instance:Testcases.Assign1@7fbdb894]" started-at="2021-11-18T20:16:25Z" name="beforeclass" finished-at="2021-11-18T20:16:26Z" duration-ms="1190" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeclass -->
        <test-method signature="login()[pri:1, instance:Testcases.Assign1@7fbdb894]" started-at="2021-11-18T20:16:26Z" name="login" finished-at="2021-11-18T20:16:26Z" duration-ms="39" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[URL did not load: oppo]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: URL did not load: oppo
	at org.testng.Assert.fail(Assert.java:93)
	at Utils.Utilities.navigateURL(Utilities.java:44)
	at Testcases.Assign1.login(Assign1.java:18)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="close()[pri:0, instance:Testcases.Assign1@7fbdb894]" started-at="2021-11-18T20:16:27Z" name="close" finished-at="2021-11-18T20:16:27Z" duration-ms="135" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- Testcases.Assign1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
